//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Core.Framework.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueueResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueueResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Core.Framework.Storage.QueueResource", typeof(QueueResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred clearing the queue..
        /// </summary>
        internal static string QueueClearError {
            get {
                return ResourceManager.GetString("QueueClearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read storage account settings from the application configuration..
        /// </summary>
        internal static string QueueConfigurationError {
            get {
                return ResourceManager.GetString("QueueConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating the {0} queue..
        /// </summary>
        internal static string QueueCreationError {
            get {
                return ResourceManager.GetString("QueueCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred deleting a message..
        /// </summary>
        internal static string QueueDeleteError {
            get {
                return ResourceManager.GetString("QueueDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred retrieving a message from the queue..
        /// </summary>
        internal static string QueueDequeueError {
            get {
                return ResourceManager.GetString("QueueDequeueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred submitting a message to the queue..
        /// </summary>
        internal static string QueueEnqueueError {
            get {
                return ResourceManager.GetString("QueueEnqueueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred extending the lease time of a message..
        /// </summary>
        internal static string QueueExtendLeaseError {
            get {
                return ResourceManager.GetString("QueueExtendLeaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue names must be less than 63 characters..
        /// </summary>
        internal static string QueueNameTooLong {
            get {
                return ResourceManager.GetString("QueueNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue names must be greater than 3 characters..
        /// </summary>
        internal static string QueueNameTooShort {
            get {
                return ResourceManager.GetString("QueueNameTooShort", resourceCulture);
            }
        }
    }
}
