//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Core.Utilities.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Core.Utilities.Diagnostics.DiagnosticsResources", typeof(DiagnosticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value passed to {0}. The maximum value of {1} is {2}.
        /// </summary>
        internal static string AboveMaximumIntErrorFormat {
            get {
                return ResourceManager.GetString("AboveMaximumIntErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly-level error, warning, info, verbose trace switch..
        /// </summary>
        internal static string AssemblyTraceLevelSwitch {
            get {
                return ResourceManager.GetString("AssemblyTraceLevelSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSERTION FAILED!.
        /// </summary>
        internal static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSERTION FAILED:  {0}.
        /// </summary>
        internal static string AssertionFailed2Format {
            get {
                return ResourceManager.GetString("AssertionFailed2Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSERTION FAILED:  {0}.
        /// </summary>
        internal static string AssertionFailedFormat {
            get {
                return ResourceManager.GetString("AssertionFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach process to the debugger.  Maybe you&apos;ll get lucky....
        /// </summary>
        internal static string AttachToDebuggerMessage {
            get {
                return ResourceManager.GetString("AttachToDebuggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; not found in &apos;{1}&apos;..
        /// </summary>
        internal static string AttributeNotFoundInFormat {
            get {
                return ResourceManager.GetString("AttributeNotFoundInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value passed to {0}. The minimum value of {1} is {2}.
        /// </summary>
        internal static string BelowMinimumIntErrorFormat {
            get {
                return ResourceManager.GetString("BelowMinimumIntErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller not authorized..
        /// </summary>
        internal static string CallerNotAuthorized {
            get {
                return ResourceManager.GetString("CallerNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the location of MSCORLIB.DLL.
        /// </summary>
        internal static string CanNotFindMscorelibError {
            get {
                return ResourceManager.GetString("CanNotFindMscorelibError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} does not exist.
        /// </summary>
        internal static string DirectoryDoesNotExistErrorFormat {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExistErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty {0} array was passed to {1}.
        /// </summary>
        internal static string EmptyArrayErrorFormat {
            get {
                return ResourceManager.GetString("EmptyArrayErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty {0} list was passed to {1}.
        /// </summary>
        internal static string EmptyListErrorFormat {
            get {
                return ResourceManager.GetString("EmptyListErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty or null argument name was passed to the ArgumentValidator.
        /// </summary>
        internal static string EmptyOrNullArgumentNamePassedToArgumentValidator {
            get {
                return ResourceManager.GetString("EmptyOrNullArgumentNamePassedToArgumentValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty or null source was passed to the ArgumentValidator.
        /// </summary>
        internal static string EmptyOrNullSourcePassedToArgumentValidator {
            get {
                return ResourceManager.GetString("EmptyOrNullSourcePassedToArgumentValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty {0} string was passed to {1}.
        /// </summary>
        internal static string EmptyStringErrorFormat {
            get {
                return ResourceManager.GetString("EmptyStringErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to the {0} custom event log.\n\nError Details: {1}\n\nOriginal Error: {2}.
        /// </summary>
        internal static string ErrorWritingToCustomEventLogFormat {
            get {
                return ResourceManager.GetString("ErrorWritingToCustomEventLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log Source does not exist: {0}.
        /// </summary>
        internal static string EventLogSourceDoesNotExist {
            get {
                return ResourceManager.GetString("EventLogSourceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception being reported at:.
        /// </summary>
        internal static string ExceptionBeingReportedAt {
            get {
                return ResourceManager.GetString("ExceptionBeingReportedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ExceptionMessageFormatterFormat {
            get {
                return ResourceManager.GetString("ExceptionMessageFormatterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :{0}.
        /// </summary>
        internal static string ExceptionMessageSeparatorFormat {
            get {
                return ResourceManager.GetString("ExceptionMessageSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception is being logged for diagnostic purposes. It is possible for exceptions to be logged during the normal operation of the software. Exceptions are included in increasing order of specificity.{0}{0}.
        /// </summary>
        internal static string ExLogHeaderFormat {
            get {
                return ResourceManager.GetString("ExLogHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *********************************************{0}{0}Exception Source: {1}{0}Exception Message:{0}{0}{2}{0}.
        /// </summary>
        internal static string ExLogMessageFormat {
            get {
                return ResourceManager.GetString("ExLogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Stack Trace:{0}{0}{1}{0}.
        /// </summary>
        internal static string ExLogTraceFormat {
            get {
                return ResourceManager.GetString("ExLogTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse config data in: &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToParseConfigDataFormat {
            get {
                return ResourceManager.GetString("FailedToParseConfigDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setup FileSystemWatcher on config file: &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToSetupFileSystemWatcherErrorFormat {
            get {
                return ResourceManager.GetString("FailedToSetupFileSystemWatcherErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not exist.
        /// </summary>
        internal static string FileDoesNotExistErrorFormat {
            get {
                return ResourceManager.GetString("FileDoesNotExistErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that you selected the correct path and try again..
        /// </summary>
        internal static string FileOrDirectoryNotFoundExceptionContent {
            get {
                return ResourceManager.GetString("FileOrDirectoryNotFoundExceptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatException failure occurred during output trace message &apos;{0}&apos;.
        /// </summary>
        internal static string FormatExceptionFailureOccurredDuringOutputTraceFormat {
            get {
                return ResourceManager.GetString("FormatExceptionFailureOccurredDuringOutputTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} handled the following exception.
        /// </summary>
        internal static string HandledTheFollowingExceptionFormat {
            get {
                return ResourceManager.GetString("HandledTheFollowingExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An type that is not an interface &apos;{0}&apos; was passed to {1}.
        /// </summary>
        internal static string InterfaceExpectedErrorFormat {
            get {
                return ResourceManager.GetString("InterfaceExpectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} array was passed to {1} which had an unexpected number of elements (expected number of elements was {3}, received {2})..
        /// </summary>
        internal static string InvalidArrayLengthErrorFormat {
            get {
                return ResourceManager.GetString("InvalidArrayLengthErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value passed to {0}.  The value of the {1} string argument (&apos;{2}&apos;) string does not match the specified the regular expression &apos;{3}&apos; (with options=&apos;{4}&apos;).
        /// </summary>
        internal static string InvalidRegExpresionErrorFormat {
            get {
                return ResourceManager.GetString("InvalidRegExpresionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.  Trace logging is already disabled..
        /// </summary>
        internal static string InvalidStateTraceLoggingIsAlreadyDisabled {
            get {
                return ResourceManager.GetString("InvalidStateTraceLoggingIsAlreadyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state.  Trace logging is already enabled..
        /// </summary>
        internal static string InvalidStateTraceLoggingIsAlreadyEnabled {
            get {
                return ResourceManager.GetString("InvalidStateTraceLoggingIsAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid {0} was passed to {1}. The maximum length of {0} is {2}.
        /// </summary>
        internal static string InvalidStringLengthErrorFormat {
            get {
                return ResourceManager.GetString("InvalidStringLengthErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of an unexpected type &apos;{0}&apos; was passed to {1} (expected type was &apos;{2}&apos;).
        /// </summary>
        internal static string InvalidTypeErrorFormat {
            get {
                return ResourceManager.GetString("InvalidTypeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid value was passed to {0}.  The value of the {1} string argument (&apos;{2}&apos;) must represent an absolute-path Uri..
        /// </summary>
        internal static string InvalidUriErrorFormat {
            get {
                return ResourceManager.GetString("InvalidUriErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid value was passed to {0}.  The value of the {1} string argument (&apos;{2}&apos;) could not be used to construct a valid Uri..
        /// </summary>
        internal static string InvalidUriStringErrorFormat {
            get {
                return ResourceManager.GetString("InvalidUriStringErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for enum type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidValueForEnumTypeFormat {
            get {
                return ResourceManager.GetString("InvalidValueForEnumTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly does not have the AssemblyConfigurationFileVersion attribute..
        /// </summary>
        internal static string MissingAssemblyConfigFileVersionError {
            get {
                return ResourceManager.GetString("MissingAssemblyConfigFileVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null {0} was passed to {1}.
        /// </summary>
        internal static string NullIntPtrError {
            get {
                return ResourceManager.GetString("NullIntPtrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null {0} reference was passed to {1}.
        /// </summary>
        internal static string NullReferenceErrorFormat {
            get {
                return ResourceManager.GetString("NullReferenceErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a shorter path or type a shorter file name..
        /// </summary>
        internal static string PathTooLongExceptionContent {
            get {
                return ResourceManager.GetString("PathTooLongExceptionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of an unexpected type &apos;{0}&apos; was passed to {1} (expected type was a subclass of &apos;{2}&apos;).
        /// </summary>
        internal static string UnexpectedTypeErrorFormat {
            get {
                return ResourceManager.GetString("UnexpectedTypeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} encountered an exception that it could not handle.
        /// </summary>
        internal static string UnhandledExceptionErrorFormat {
            get {
                return ResourceManager.GetString("UnhandledExceptionErrorFormat", resourceCulture);
            }
        }
    }
}
